title: Receiver Remote
description: An Apple Watch remote for Yamaha network receivers.
theme: minima
url: https://anthonyfenn.github.io
baseurl: /ReceiverRemoteSupportSite

header_pages:
  - index.md
  - privacy.md
